const express = require('express'); //chama a biblioteca express
const cors = require('cors'); ////chama a biblioteca cors
const { application } = require('express');

const server = express(); //define o express como uma variavel que vai chamar os métodos GET, POST, DELETE e

server.use(express.static('public'));
server.use(cors());

let artigos =[
    {
        id: 1,
        trilha: 'trilha 1',
        titulo: 'O que é informática?',
        subtitulo: 'Abrem-se as portas de um novo universo...',
        texto1: "A informática é o campo do conhecimento que leva em conta as relações existentes entre as pessoas e a informação por meio da construção de interfaces, novas tecnologias e sistemas direcionados para a solução ou para a automatização de problemas. ",
        img1: '/assets/trilha1/1.png',
        texto2: "Atualmente, os conhecimentos de informática são cada vez mais necessários para que os indivíduos tornem-se tecnologicamente autônomos, uma vez que é crescente a adoção de interfaces e sistemas completamente informatizados.",
        img2: '/assets/trilha1/2.png',
        mp: '...',
        planetaImg: "/assets/planeta-rosinha.png",
        ind1Titulo: 'O que é Algoritmo',
        ind1Desc:'Neste vídeo, a desenvolvedora  Rafa Ballerini explica um dos conceitos iniciais da programação e do universo de TI.',
        ind1Link:'https://youtu.be/dvNp575fwzQ',
        ind2Titulo: 'Podcast Quero ser Dev',
        ind2Desc:'Neste episódio, a desenvolvedora Simara Conceição apresenta conceitos introdutórios para quem quer seguir na TI.',
        ind2Link:'https://open.spotify.com/episode/5CylM17tMacnRaFonQn6tB?si=25ac7cfc75234a73',
        ind3Titulo: 'PrograMaria Fala',
        ind3Desc:'Nesta entrevista, a diretora sênior Lúcia Ishido retrata sua experiência com a área de TI, gestão e liderança de pessoas.',
        ind3Link:'https://www.programaria.org/programaria-fala-lucia-ishido/ ',
        ind4Titulo: 'O jogo da imitação',
        ind4Desc:'O filme retrata a história Alan Turing e a decodificação de uma máquina utilizada pelos nazistas durante a Segunda Guerra Mundial.',
        ind4Link:' https://www.netflix.com/watch/70295172?source=35',
    },
    {
        id: 2,
        trilha: 'trilha 1',
        titulo: 'O que são aplicações?',
        subtitulo: 'Entenda um pouco mais sobre as bases da informática',
        texto1: 'Segundo o Glossário da Sociedade de Informação, uma aplicação é um programa ou um conjunto de programas concebido para ajudar o utilizador a realizar uma tarefa específica ou múltiplas tarefas relacionadas.',
        img1: '/assets/trilha1/3.png',
        texto2: 'Assim, as aplicações atuam integrando demandas de um público alvo com inovações tecnológivas. Programas de base como sistema soperacionais (Windows e Linux, por exemplo) não são aplicações.',
        img2: '/assets/trilha2/4.png',
        mp: '...',
        planetaImg: "/assets/planeta-rosinha.png",
        ind1Titulo: 'O que é Algoritmo',
        ind1Desc:'Neste vídeo, a desenvolvedora  Rafa Ballerini explica um dos conceitos iniciais da programação e do universo de TI.',
        ind1Link:'https://youtu.be/dvNp575fwzQ',
        ind2Titulo: 'Podcast Quero ser Dev',
        ind2Desc:'Neste episódio, a desenvolvedora Simara Conceição apresenta conceitos introdutórios para quem quer seguir na TI.',
        ind2Link:'https://open.spotify.com/episode/5CylM17tMacnRaFonQn6tB?si=25ac7cfc75234a73',
        ind3Titulo: 'PrograMaria Fala',
        ind3Desc:'Nesta entrevista, a diretora sênior Lúcia Ishido retrata sua experiência com a área de TI, gestão e liderança de pessoas.',
        ind3Link:'https://www.programaria.org/programaria-fala-lucia-ishido/ ',
        ind4Titulo: 'O jogo da imitação',
        ind4Desc:'O filme retrata a história Alan Turing e a decodificação de uma máquina utilizada pelos nazistas durante a Segunda Guerra Mundial.',
        ind4Link:' https://www.netflix.com/watch/70295172?source=35',
    },
    {
        id: 3,
        trilha: 'trilha 1',
        titulo: 'Onde está a informática no mundo?',
        subtitulo: 'Após sua grande explosão, ela está cada vez mais presente nas nossas vidas',
        texto1: 'A Informática surge durante a década de 40 com objetivo de estudar e desenvolver de tecnologias as quais substituíssem ou facilitassem atividades antes estritamente humanas, sendo muito inovadoras para a época.Com o passar dos anos, tomou a forma de uma ferramenta imprescindível no dia a dia.',
        img1: '/assets/trilha1/5.png',
        texto2: 'Desde a criação do correio eletrônico, desenvolvido pelo engenheiro Ray Tomlinson em meados de 1971 - que viabilizou o envio de informações, até a aplicação de softwares de gestão organizacional, responsáveis por armazenar dados e sistematizar tarefas. As aplicações estão nos blogs na internet, nos aplicativos dos celulares e nas redes sociais',
        img2: '/assets/trilha1/6.png',
        mp: '...',
        planetaImg: "/assets/planeta-rosinha.png",
        ind1Titulo: 'O que é Algoritmo',
        ind1Desc:'Neste vídeo, a desenvolvedora  Rafa Ballerini explica um dos conceitos iniciais da programação e do universo de TI.',
        ind1Link:'https://youtu.be/dvNp575fwzQ',
        ind2Titulo: 'Podcast Quero ser Dev',
        ind2Desc:'Neste episódio, a desenvolvedora Simara Conceição apresenta conceitos introdutórios para quem quer seguir na TI.',
        ind2Link:'https://open.spotify.com/episode/5CylM17tMacnRaFonQn6tB?si=25ac7cfc75234a73',
        ind3Titulo: 'PrograMaria Fala',
        ind3Desc:'Nesta entrevista, a diretora sênior Lúcia Ishido retrata sua experiência com a área de TI, gestão e liderança de pessoas.',
        ind3Link:'https://www.programaria.org/programaria-fala-lucia-ishido/ ',
        ind4Titulo: 'O jogo da imitação',
        ind4Desc:'O filme retrata a história Alan Turing e a decodificação de uma máquina utilizada pelos nazistas durante a Segunda Guerra Mundial.',
        ind4Link:' https://www.netflix.com/watch/70295172?source=35',
    },
    {
        id: 4,
        trilha: 'trilha 1',
        titulo: 'De que as aplicações são feitas?',
        subtitulo: 'Navegue pela matrix do universo da informática',
        texto1: 'A TI possui finalidades estabelecidas na criação de novos recursos, por isso a nossa visualização de um software é apenas a ponta do iceberg em um processo que inicia com documentos e finaliza na concretização de funcionalidades, ou seja, a programação e implementação.',
        img1: '/assets/trilha1/7.png',
        texto2: 'A documentação deve expor como se darão as etapas de fundamentação do projeto, além de quais serão suas propriedades do sistema e/ou software e, claro, suas aplicações mais determinantes (ENGINEERING, 2022). Já a programação, segundo o Progra{m}aria (2015), é de forma simples: “[...] dar ordens para que os computadores façam o que você quer que eles façam”',
        img2: '/assets/trilha1/8.png',
        mp: '...',
        planetaImg: "/assets/planeta-rosinha.png",
        ind1Titulo: 'O que é Algoritmo',
        ind1Desc:'Neste vídeo, a desenvolvedora  Rafa Ballerini explica um dos conceitos iniciais da programação e do universo de TI.',
        ind1Link:'https://youtu.be/dvNp575fwzQ',
        ind2Titulo: 'Podcast Quero ser Dev',
        ind2Desc:'Neste episódio, a desenvolvedora Simara Conceição apresenta conceitos introdutórios para quem quer seguir na TI.',
        ind2Link:'https://open.spotify.com/episode/5CylM17tMacnRaFonQn6tB?si=25ac7cfc75234a73',
        ind3Titulo: 'PrograMaria Fala',
        ind3Desc:'Nesta entrevista, a diretora sênior Lúcia Ishido retrata sua experiência com a área de TI, gestão e liderança de pessoas.',
        ind3Link:'https://www.programaria.org/programaria-fala-lucia-ishido/ ',
        ind4Titulo: 'O jogo da imitação',
        ind4Desc:'O filme retrata a história Alan Turing e a decodificação de uma máquina utilizada pelos nazistas durante a Segunda Guerra Mundial.',
        ind4Link:' https://www.netflix.com/watch/70295172?source=35',
    },
    {
        id: 5,
        trilha: 'Trilha1',
        titulo: 'Mitos da Informática',
        subtitulo: 'Desmistificando o universo para facilitar a jornada.',
        texto1: 'Apesar de ser uma área bastante popular nos dias de hoje, muitos ainda acreditam que a informática se resume apenas a atividades pontuais, como a manutenção de computadores, ou a criação de tabelas básicas no Excel. Porém, instalações, programação de redes e softwares, montagem e acabamento de computadores, correção de problemas em aparelhos eletrônicos, são também possibilidades para quem pretende atuar no campo tecnológico.',
        img1: '/assets/trilha1/9.png',
        texto2: 'Ao mesmo tempo a ideia de que atuar no mundo informatizado é um caminho certeiro para o sucesso financeiro não pode ser subestimado. Isso porque mesmo sendo um campo profissional em crescimento, ainda necessita de capacitação igualmente proporcional, não anulando a ampla concorrência. E quem disse que TI é coisa de homem? Apesar deles serem a maioria no mercado, qualquer pessoa pode ingressar na área.',
        img2: '/assets/trilha2/10.png',
        mp: '...',
        planetaImg: "/assets/planeta-rosinha.png",
        ind1Titulo: 'O que é Algoritmo',
        ind1Desc:'Neste vídeo, a desenvolvedora  Rafa Ballerini explica um dos conceitos iniciais da programação e do universo de TI.',
        ind1Link:'https://youtu.be/dvNp575fwzQ',
        ind2Titulo: 'Podcast Quero ser Dev',
        ind2Desc:'Neste episódio, a desenvolvedora Simara Conceição apresenta conceitos introdutórios para quem quer seguir na TI.',
        ind2Link:'https://open.spotify.com/episode/5CylM17tMacnRaFonQn6tB?si=25ac7cfc75234a73',
        ind3Titulo: 'PrograMaria Fala',
        ind3Desc:'Nesta entrevista, a diretora sênior Lúcia Ishido retrata sua experiência com a área de TI, gestão e liderança de pessoas.',
        ind3Link:'https://www.programaria.org/programaria-fala-lucia-ishido/ ',
        ind4Titulo: 'O jogo da imitação',
        ind4Desc:'O filme retrata a história Alan Turing e a decodificação de uma máquina utilizada pelos nazistas durante a Segunda Guerra Mundial.',
        ind4Link:' https://www.netflix.com/watch/70295172?source=35',
    },
    {
        id: 6,
        trilha: 'Trilha2',
        titulo: 'Importância da Ciência',
        subtitulo: 'Novo planeta, novas possibilidades e problemas',
        texto1: 'A ciência tem por objetivo encontrar respostas ou soluções para problemáticas que dizem respeito à sociedade ou instituições sociais. Ela pode ser considerada o meio pelo qual a tecnologia se desenvolveu, afinal, foi através de um questionamento ou desejo de se criar uma inovação tecnológica que a ciência foi trazendo evoluções.',
        img1: '/assets/trilha2/1.png',
        texto2: 'Ciência e tecnologia estão diretamente ligadas, pois à medida que métodos de investigação progridem com auxílio da tecnologia, a ciência ganha novas metodologias de análise que podem ser mais precisas em seus resultados. Essa troca vem proporcinando grandes avanços para a humanidade.',
        img2: '/assets/trilha2/2.png',
        mp: '...',
        planetaImg: "/assets/planeta-amarelo.png",
        ind1Titulo: '',
        ind1Desc:'',
        ind1Link:'',
        ind2Titulo: '',
        ind2Desc:'',
        ind2Link:'',
        ind3Titulo: '',
        ind3Desc:'',
        ind3Link:'',
        ind4Titulo: '',
        ind4Desc:'',
        ind4Link:''
    },
    {
        id: 7,
        trilha: 'Trilha2',
        titulo: 'Mitos da Ciência',
        subtitulo: 'Desmistificando a ciência e sua relação com a criatividade',
        texto1: 'Existem um campo da ciência que se dedica a desmitificar creças erradas que temos sobre a mesma. Primeiro que nem tudo na precisa ser experiementado, há estudos que usam outras pesquisas como fontes. Em segundo lugar ela não é rígida, não há uma unica forma de contruir o conhecimento.',
        img1: '/assets/trilha2/3.png',
        texto2: 'Para superar esses mitos é importante que a visão do “cientista maluco genial” seja desvinculada da ciência. Todo mundo pode ser um ciêntista e são várias as áreas para explorar. Para isso é preciso ter em mente que ela pode ser produzida a partir de uma acumulação de conhecimentos dinâmica e flexível na escolha de metodologias, levando em conta conceitos como a criatividade.',
        img2: '/assets/trilha2/4.png',
        mp: '...',
        planetaImg: "/assets/planeta-amarelo.png",
        ind1Titulo: '',
        ind1Desc:'',
        ind1Link:'',
        ind2Titulo: '',
        ind2Desc:'',
        ind2Link:'',
        ind3Titulo: '',
        ind3Desc:'',
        ind3Link:'',
        ind4Titulo: '',
        ind4Desc:'',
        ind4Link:''
    },
    {
        id: 8,
        trilha: 'Trilha2',
        titulo: 'Criatividade',
        subtitulo: 'Um pontinho no meio do universo que vira uma galáxia.',
        texto1: 'texto1',
        img1: '/assets/trilha2/5.png',
        texto2: 'texto2',
        img2: '/assets/trilha2/6.png',
        mp: '...',
        planetaImg: "/assets/planeta-amarelo.png",
        ind1Titulo: '',
        ind1Desc:'',
        ind1Link:'',
        ind2Titulo: '',
        ind2Desc:'',
        ind2Link:'',
        ind3Titulo: '',
        ind3Desc:'',
        ind3Link:'',
        ind4Titulo: '',
        ind4Desc:'',
        ind4Link:''
    },
    {
        id: 9,
        trilha: 'Trilha2',
        titulo: 'Desenvolvendo Projetos, por quê?',
        subtitulo: '',
        texto1: 'Surgindo com o pretexto principal de viabilizar o vínculo entre os pilares de pesquisa, ensino e sociedade, os projetos são elaborações com enfoque em deficiências reais, sustentadas por ideias que se despertam nos mais diversos cenários. Podem ser feitos individualmente, ou em grupo, trabalhando diferentes eixos e problematicas.',
        img1: '/assets/trilha2/7.png',
        texto2: 'Dentro do âmbito profissional pessoal, estar inserido em um projeto significa estar aberto a maiores oportunidades para sua carreira, isso porque esse processo torna-se um facilitador de relações, influenciando um networking de sucesso, por exemplo.',
        img2: '/assets/trilha2/8.png',
        mp: '...',
        planetaImg: "/assets/planeta-amarelo.png",
        ind1Titulo: '',
        ind1Desc:'',
        ind1Link:'',
        ind2Titulo: '',
        ind2Desc:'',
        ind2Link:'',
        ind3Titulo: '',
        ind3Desc:'',
        ind3Link:'',
        ind4Titulo: '',
        ind4Desc:'',
        ind4Link:''
    },
    {
        id: 10,
        trilha: 'Trilha2',
        titulo: 'Etapas da criação de um projeto',
        subtitulo: 'Um guia para tirar as suas ideias do papel e explorar sua criaitividade.',
        texto1: 'De forma objetiva, podemos resumir o processo de criação d eum projeto em 6 etapas: ideia, estudo, planejamento, investimento, execução e aperfeiçoamento. Cada uma delas necessita de estudo e deidcação, mas podem ser simplificadas através de algumas estratégias.',
        img1: '/assets/trilha2/9.png',
        texto2: 'É possível buscar instituições que abracem causas, valorizem ideias e ofereçam suporte, dando oportunidade para um crescimento referente tanto à visibilidade quanto aos recursos adicionais que forem necessários para aplicar aquilo que foi pensado. Outra estratégia é a divulgação em plataformas digitais, voltando as postagens para o público-alvo do projeto e possibilitando a corroboração de demais personalidades ao redor do mundo.',
        img2: '/assets/trilha2/10.png',
        mp: '...',
        planetaImg: "/assets/planeta-amarelo.png",
        ind1Titulo: '',
        ind1Desc:'',
        ind1Link:'',
        ind2Titulo: '',
        ind2Desc:'',
        ind2Link:'',
        ind3Titulo: '',
        ind3Desc:'',
        ind3Link:'',
        ind4Titulo: '',
        ind4Desc:'',
        ind4Link:''
    },
    {
        id: 11,
        trilha: 'Trilha3',
        titulo: 'Desenvolvimento Web',
        subtitulo: 'Conhecndo as bases do idioma da web',
        texto1: 'O Desenvolvimento Web comporta o conjunto de atividades referentes à criação de sites, apps, softwares, bancos de dados e demais ferramentas que constroem o universo da internet.Dentro da carreira de desenvolvedor web existem especialidades que podem ser escolhidas, a exemplo dos tão falados “front-end” e “back-end”, infraestrutura de sistemas, especialistas em banco de dados, etc.',
        img1: '/assets/trilha3/1.png',
        texto2: 'Dentre os pontos de união entre todas as especialidades deste mercado estão a necessidade de constante atualização, e uma grande comunidade ao redor do mundo que se auxilia mutuamente através de diversos fóruns e redes sociais pela internet. As tecnologias base para o desenvolvimento web são as linguagens: HTML, CSS  e JavaScript.',
        img2: '/assets/trilha3/2.png',
        mp: '...',
        planetaImg: "/assets/planeta-rosa.png",
        ind1Titulo: 'Diferentes Carreiras em Tecnologia',
        ind1Desc:'A desenvolvevdora Rafa Ballerini apresenta diferentes carreiras em TI, inclusive além da programação',
        ind1Link:'https://www.youtube.com/watch?v=3gPZ02Iqr-0',
        ind2Titulo: 'PodProgramar',
        ind2Desc:'Ep. 78 - Mudança de carreira. As convidadas desse episódio largaram suas profissões para aprender a programar.',
        ind2Link:'https://podprogramar.com.br/pp-78-mudanca-de-carreira/',
        ind3Titulo: '',
        ind3Desc:'',
        ind3Link:'',
        ind4Titulo: '',
        ind4Desc:'',
        ind4Link:''
    },
    {
        id: 12,
        trilha: 'Trilha3',
        titulo: 'Desenvolvimento de Jogos',
        subtitulo: 'Os avanços da era gamer.',
        texto1: 'O Desenvolvimento de Jogos compreende o processo de união de elementos gráficos, de áudio, e os demais recursos que garantam a funcionalidade do produto através do aparelho do usuário que está jogando. Para isso, faz-se necessária a criação de um código-fonte, que inclua as funções de inteligência artificial e os códigos de gerenciamento capazes de interpretar os comandos dos personagens - papel desempenhado pelo profissional ou equipe de profissionais de programação.',
        img1: '/assets/trilha3/3.png',
        texto2: 'O desenvolvimento dos mapas do jogo - atribuído ao level designer, a testagem das funcionalidades, que garantem que o jogo está rodando de acordo com o planejamento - papel dos analistas de testes; além do trabalho de edição de som, liderança de projetos, etc. dispostas de acordo com a organização da equipe de criação. Assim como qualquer outro nicho da informática, cursos de programação alinhados com as necessidades de aprendizagem são a chave para quem deseja fazer parte do processo de criação de jogos.',
        img2: '/assets/trilha3/4.png',
        mp: '...',
        planetaImg: "/assets/planeta-rosa.png",
        ind1Titulo: 'Diferentes Carreiras em Tecnologia',
        ind1Desc:'A desenvolvevdora Rafa Ballerini apresenta diferentes carreiras em TI, inclusive além da programação',
        ind1Link:'https://www.youtube.com/watch?v=3gPZ02Iqr-0',
        ind2Titulo: 'PodProgramar',
        ind2Desc:'Ep. 78 - Mudança de carreira. As convidadas desse episódio largaram suas profissões para aprender a programar.',
        ind2Link:'https://podprogramar.com.br/pp-78-mudanca-de-carreira/',
        ind3Titulo: '',
        ind3Desc:'',
        ind3Link:'',
        ind4Titulo: '',
        ind4Desc:'',
        ind4Link:''
    },
    {
        id: 13,
        trilha: 'Trilha3',
        titulo: 'Desenvolvimento Mobile',
        subtitulo: 'Desbravando o universo dos aplicativos de celular',
        texto1: 'O desenvolvimento mobile é a esfera que foca na criação de inovações com foco em smartphones, tablets, wearables e até mesmo brinquedos tecnológicos. A sua importância está atrelada ao fato do percentual de usuários de dispositivos móveis ser maior do que de outros, tendo como consequência um consumo superior do público que, constantemente, está a procura de atualizações.',
        img1: '/assets/trilha3/5.png',
        texto2: 'O fato dos usuários disporem de recursos na palma da mão com a mobilidade de carregar e usá-lo em qualquer lugar, aumenta sua produtividade, por isso, também é muito requerido pelas corporações. A sua implementação pode ser vista em diversos cenários, tal como o surgimento de aplicativos para bancos, que impactou o uso das filiais físicas, uma vez que os usuários têm a possibilidade de realizarem a maioria das operações remotamente',
        img2: '/assets/trilha3/6.png',
        mp: '...',
        planetaImg: "/assets/planeta-rosa.png",
        ind1Titulo: 'Diferentes Carreiras em Tecnologia',
        ind1Desc:'A desenvolvevdora Rafa Ballerini apresenta diferentes carreiras em TI, inclusive além da programação',
        ind1Link:'https://www.youtube.com/watch?v=3gPZ02Iqr-0',
        ind2Titulo: 'PodProgramar',
        ind2Desc:'Ep. 78 - Mudança de carreira. As convidadas desse episódio largaram suas profissões para aprender a programar.',
        ind2Link:'https://podprogramar.com.br/pp-78-mudanca-de-carreira/',
        ind3Titulo: '',
        ind3Desc:'',
        ind3Link:'',
        ind4Titulo: '',
        ind4Desc:'',
        ind4Link:''
    },
    {
        id: 14,
        trilha: 'Trilha3',
        titulo: 'Data Science',
        subtitulo: 'A era dos dados e da informação.',
        texto1: 'Data Science ou Ciência de Dados é o campo que coleta, analisa e comunica os dados que são armazenados com o uso das tecnologias, os transformando em informações úteis para as empresas, logo combina ciências da computação e matemática para extração de índices numéricos. A digitalização da época em que vivemos aumentou expressivamente o registro de dados, assim como a sua complexidade.',
        img1: '/assets/trilha3/7.png',
        texto2: 'Nessa lógica, os cientistas de dados entram como canais para processamento dessas informações e efetivação da criação de estratégias que mantenham o negócio, seja ele um software ou não. Uma de suas aplicações está relacionada a personalização do marketing, que customiza a experiência do usuário através da coleta de como ele se comporta perante determinados produtos.',
        img2: '/assets/trilha3/8.png',
        mp: '...',
        planetaImg: "/assets/planeta-rosa.png",
        ind1Titulo: 'Diferentes Carreiras em Tecnologia',
        ind1Desc:'A desenvolvevdora Rafa Ballerini apresenta diferentes carreiras em TI, inclusive além da programação',
        ind1Link:'https://www.youtube.com/watch?v=3gPZ02Iqr-0',
        ind2Titulo: 'PodProgramar',
        ind2Desc:'Ep. 78 - Mudança de carreira. As convidadas desse episódio largaram suas profissões para aprender a programar.',
        ind2Link:'https://podprogramar.com.br/pp-78-mudanca-de-carreira/',
        ind3Titulo: '',
        ind3Desc:'',
        ind3Link:'',
        ind4Titulo: '',
        ind4Desc:'',
        ind4Link:''
    },
    {
        id: 15,
        trilha: 'Trilha3',
        titulo: 'Machine Learning',
        subtitulo: 'A aprendizagem de máquina.',
        texto1: 'Machine Learning é a área de estudo que se sustenta no conceito de Aprendizado de Máquina, ou seja, que com a análise de dados máquinas possam compreender comportamentos humanos e realizar previsões sem que o desenvolvedor precise intervir (ou com o mínimo dela), por isso, pode ser considerada uma ferramenta do cientista de dados.',
        img1: '/assets/trilha3/9.png',
        texto2: 'No cenário hodierno tem se tornado relevante no mercado, pois apresenta limitações ínfimas com relação aos seres humanos, tendo em conta sua velocidade, precisão, pouca recorrência de falhas e verificação automatizada. A machine learning pode ser percebida em algoritmos de pesquisa como o Google, em que os dados monitorados geram um aprendizado para a máquina, possibilitando que ela identifique qual é a resposta mais adequada para o usuário.',
        img2: '/assets/trilha3/10.png',
        mp: '...',
        planetaImg: "/assets/planeta-rosa.png",
        ind1Titulo: 'Diferentes Carreiras em Tecnologia',
        ind1Desc:'A desenvolvevdora Rafa Ballerini apresenta diferentes carreiras em TI, inclusive além da programação',
        ind1Link:'https://www.youtube.com/watch?v=3gPZ02Iqr-0',
        ind2Titulo: 'PodProgramar',
        ind2Desc:'Ep. 78 - Mudança de carreira. As convidadas desse episódio largaram suas profissões para aprender a programar.',
        ind2Link:'https://podprogramar.com.br/pp-78-mudanca-de-carreira/',
        ind3Titulo: '',
        ind3Desc:'',
        ind3Link:'',
        ind4Titulo: '',
        ind4Desc:'',
        ind4Link:''
    },
    {
        id: 16,
        trilha: 'Trilha4',
        titulo: 'Ada Lovelace',
        subtitulo: 'A primeira progrmadora da história.',
        texto1: 'Popularmente conhecida como Ada Lovelace, Augusta Ada Byron King (1815-1852) foi uma matemática e escritora inglesa, considerada a primeira programadora da história entre homens e mulheres. Quando pequena, a mãe de Ada promoveu seu interesse pela matemática e a lógica para que não seguisse os passos de seu pai, o poeta Lord Byron. Ela tinha o sonho de voar e tentou realizar esse sonho durante  a adolescência escrevendo inclusive um livro sobre o assunto.',
        img1: '/assets/trilha4/1.png',
        texto2: 'Ada criou o que é considerado o primeiro algoritmo de computador para a Máquina Analítica de Charles Babbage, capaz de realizar cálculos matemáticos. Ela traduziu o artigo sobre o projeto adicionando suas próprias notas, maiores e mais detalhadas do que o original e publicadas sob o nome de AAL. Somente em 1953 que o trabalho foi reconhecido como a descrição do primeiro computador e software da história.',
        img2: '/assets/trilha4/2.png',
        mp: '...',
        planetaImg: "/assets/planeta-azul.png",
        ind1Titulo: 'Mulheres na Computação',
        ind1Desc:'Nesse TEDx Talk, a cientista da computação Camila Achutti traça o cenário brasileiro das mulheres na tecnologia.',
        ind1Link:'https://www.youtube.com/watch?v=Qq9h2vVBZmQ',
        ind2Titulo: '#73 Margaret Hamilton',
        ind2Desc:'Nesse episódio do PodProgramar as meninas contam a biografia de uma das programadoras responsáveis por enviar o homem a Lua.',
        ind2Link:'https://podprogramar.com.br/podprogramar-73-margaret-hamilton-opodcastedelas/',
        ind3Titulo: 'Por que o machismo cria barreiras para as mulheres na tecnologia?',
        ind3Desc:'Artigo do projeto Progra{m}aria',
        ind3Link:'https://www.programaria.org/especiais/mulheres-tecnologia/',
        ind4Titulo: 'Estrelas Além do Tempo',
        ind4Desc:'Conheça a história de Katherine Johnson, Dorothy Vaughan e Mary Jackson três matemáticas da NASA no auge da corrida espacial.',
        ind3Link:'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiF4fCPwoX8AhVWD7kGHfFqCycQFnoECB0QAw&url=https%3A%2F%2Fwww.disneyplus.com%2Fpt-br%2Fmovies%2Festrelas-alem-do-tempo%2F2xa2YdiOJXQt&usg=AOvVaw2AqEcGiW1tBDpfIqpHCT5o',
    },
    {
        id: 17,
        trilha: 'Trilha4',
        titulo: 'Grace Hopper',
        subtitulo: 'Precursora da COBOL',
        texto1: 'Considerada a mãe da programação de computadores, Grace Hopper, doutora em matemática pela faculdade de Yale, foi a criadora da Linguagem Comum Orientada para Negócios (COBOL, na sigla em inglês), a primeira linguagem complexa de computador , que é utilizada até hoje por empresas em todo mundo. ',
        img1: '/assets/trilha4/3.png',
        texto2: 'Durante a Segunda Guerra Mundial, quando abandonou seu cargo de professora para ingressar na marinha e chegou ao cargo de contra-almirante, além de programar o primeiro computador de grande capacidade, o Mark I, também foi a responsável por batizar os problemas inesperados em hardware ou software de “bugs”, como conhecemos hoje.',
        img2: '/assets/trilha4/4.png',
        mp: '...',
        planetaImg: "/assets/planeta-azul.png",
        ind1Titulo: 'Mulheres na Computação',
        ind1Desc:'Nesse TEDx Talk, a cientista da computação Camila Achutti traça o cenário brasileiro das mulheres na tecnologia.',
        ind1Link:'https://www.youtube.com/watch?v=Qq9h2vVBZmQ',
        ind2Titulo: '#73 Margaret Hamilton',
        ind2Desc:'Nesse episódio do PodProgramar as meninas contam a biografia de uma das programadoras responsáveis por enviar o homem a Lua.',
        ind2Link:'https://podprogramar.com.br/podprogramar-73-margaret-hamilton-opodcastedelas/',
        ind3Titulo: 'Por que o machismo cria barreiras para as mulheres na tecnologia?',
        ind3Desc:'Artigo do projeto Progra{m}aria',
        ind3Link:'https://www.programaria.org/especiais/mulheres-tecnologia/',
        ind4Titulo: 'Estrelas Além do Tempo',
        ind4Desc:'Conheça a história de Katherine Johnson, Dorothy Vaughan e Mary Jackson três matemáticas da NASA no auge da corrida espacial.',
        ind3Link:'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiF4fCPwoX8AhVWD7kGHfFqCycQFnoECB0QAw&url=https%3A%2F%2Fwww.disneyplus.com%2Fpt-br%2Fmovies%2Festrelas-alem-do-tempo%2F2xa2YdiOJXQt&usg=AOvVaw2AqEcGiW1tBDpfIqpHCT5o',
    },
    {
        id: 18,
        trilha: 'Trilha4',
        titulo: 'Dorothy Vaughan',
        subtitulo: 'Jornada nas estrelas',
        texto1: 'Dorothy Johnson Vaughan nasceu em 1910, foi uma matemática estadunidense que trabalhou na predecessora da NASA, agência espacial americana no Langley Research Center, o mais antigo centro de pesquisa de campo. Ela foi a primeira mulher negra a ser promovida a chefe da West Area Computers em uma época em que a segregação racial era muito forte nos Estados Unidos.',
        img1: '/assets/trilha4/5.png',
        texto2: 'A West Area Computers era uma área segregada da instituição exclusiva para  mulheres matemáticas negras. Dorothy se especializou em rotas de voo, Projeto Scout, e programação FORTRAN. Ela instruiu novos conceitos aos funcionários, sempre tentando combater o racismo estrutural. Sua história serviu de Inspiração para o longa Estrelas Além do Tempo.',
        img2: '/assets/trilha4/6.png',
        mp: '...',
        planetaImg: "/assets/planeta-azul.png",
        ind1Titulo: 'Mulheres na Computação',
        ind1Desc:'Nesse TEDx Talk, a cientista da computação Camila Achutti traça o cenário brasileiro das mulheres na tecnologia.',
        ind1Link:'https://www.youtube.com/watch?v=Qq9h2vVBZmQ',
        ind2Titulo: '#73 Margaret Hamilton',
        ind2Desc:'Nesse episódio do PodProgramar as meninas contam a biografia de uma das programadoras responsáveis por enviar o homem a Lua.',
        ind2Link:'https://podprogramar.com.br/podprogramar-73-margaret-hamilton-opodcastedelas/',
        ind3Titulo: 'Por que o machismo cria barreiras para as mulheres na tecnologia?',
        ind3Desc:'Artigo do projeto Progra{m}aria',
        ind3Link:'https://www.programaria.org/especiais/mulheres-tecnologia/',
        ind4Titulo: 'Estrelas Além do Tempo',
        ind4Desc:'Conheça a história de Katherine Johnson, Dorothy Vaughan e Mary Jackson três matemáticas da NASA no auge da corrida espacial.',
        ind3Link:'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiF4fCPwoX8AhVWD7kGHfFqCycQFnoECB0QAw&url=https%3A%2F%2Fwww.disneyplus.com%2Fpt-br%2Fmovies%2Festrelas-alem-do-tempo%2F2xa2YdiOJXQt&usg=AOvVaw2AqEcGiW1tBDpfIqpHCT5o',
    },
    {
        id: 19,
        trilha: 'Trilha4',
        titulo: 'Camila Achutti',
        subtitulo: 'Disseminando a igualdade de gênero',
        texto1: 'Criadora do portal “Mulheres na Computação”, uma das primeiras, mais importantes e influentes iniciativas de inclusão das mulheres no cenário contemporâneo de tecnologia, a ativista social, eleita uma das 100 Líderes do Amanhã, Camila Achutti, é fortemente reconhecida por sua proeminência no debate sobre igualdade de gêneros.',
        img1: '/assets/trilha4/7.png',
        texto2: 'Entusiasmada pela evolução de métodos e teorias de aprendizagem, ela atua, ainda, como pesquisadora educacional, e fundou, com base em suas pesquisas, o Mastertech, startup de educação eleita como a mais atraente do país em 2018.',
        img2: '/assets/trilha4/8.png',
        mp: '...',
        planetaImg: "/assets/planeta-azul.png",
        ind1Titulo: 'Mulheres na Computação',
        ind1Desc:'Nesse TEDx Talk, a cientista da computação Camila Achutti traça o cenário brasileiro das mulheres na tecnologia.',
        ind1Link:'https://www.youtube.com/watch?v=Qq9h2vVBZmQ',
        ind2Titulo: '#73 Margaret Hamilton',
        ind2Desc:'Nesse episódio do PodProgramar as meninas contam a biografia de uma das programadoras responsáveis por enviar o homem a Lua.',
        ind2Link:'https://podprogramar.com.br/podprogramar-73-margaret-hamilton-opodcastedelas/',
        ind3Titulo: 'Por que o machismo cria barreiras para as mulheres na tecnologia?',
        ind3Desc:'Artigo do projeto Progra{m}aria',
        ind3Link:'https://www.programaria.org/especiais/mulheres-tecnologia/',
        ind4Titulo: 'Estrelas Além do Tempo',
        ind4Desc:'Conheça a história de Katherine Johnson, Dorothy Vaughan e Mary Jackson três matemáticas da NASA no auge da corrida espacial.',
        ind3Link:'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiF4fCPwoX8AhVWD7kGHfFqCycQFnoECB0QAw&url=https%3A%2F%2Fwww.disneyplus.com%2Fpt-br%2Fmovies%2Festrelas-alem-do-tempo%2F2xa2YdiOJXQt&usg=AOvVaw2AqEcGiW1tBDpfIqpHCT5o',
    },
    {
        id: 20,
        trilha: 'Trilha4',
        titulo: 'Claudia Bauzer Medeiros',
        subtitulo: 'Ocupando espaços no Brasil.',
        texto1: 'Engenheira eletrotécnica, pesquisadora e professora universitária brasileira, Claudia Bauzer Medeiros é, também, uma grande incentivadora da participação de mulheres na área da computação.',
        img1: '/assets/trilha4/9.png',
        texto2: 'Ela ocupou posições importantes em agências de fomento à pesquisa; Foi presidenta da Sociedade Brasileira de Computação (SBC) de 2003 a 2017, militando pela ampliação do interesse dos jovens, em especial das meninas, em computação; E contribuiu muito para alavancar a participação de mulheres na área da computação, razão pela qual recebeu os prêmios Anita Borg Agent of Change Award (USA, 2006) e Google Brasil Award (2008).',
        img2: '/assets/trilha4/10.png',
        mp: '...',
        planetaImg: "/assets/planeta-azul.png",
        ind1Titulo: 'Mulheres na Computação',
        ind1Desc:'Nesse TEDx Talk, a cientista da computação Camila Achutti traça o cenário brasileiro das mulheres na tecnologia.',
        ind1Link:'https://www.youtube.com/watch?v=Qq9h2vVBZmQ',
        ind2Titulo: '#73 Margaret Hamilton',
        ind2Desc:'Nesse episódio do PodProgramar as meninas contam a biografia de uma das programadoras responsáveis por enviar o homem a Lua.',
        ind2Link:'https://podprogramar.com.br/podprogramar-73-margaret-hamilton-opodcastedelas/',
        ind3Titulo: 'Por que o machismo cria barreiras para as mulheres na tecnologia?',
        ind3Desc:'Artigo do projeto Progra{m}aria',
        ind3Link:'https://www.programaria.org/especiais/mulheres-tecnologia/',
        ind4Titulo: 'Estrelas Além do Tempo',
        ind4Desc:'Conheça a história de Katherine Johnson, Dorothy Vaughan e Mary Jackson três matemáticas da NASA no auge da corrida espacial.',
        ind3Link:'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiF4fCPwoX8AhVWD7kGHfFqCycQFnoECB0QAw&url=https%3A%2F%2Fwww.disneyplus.com%2Fpt-br%2Fmovies%2Festrelas-alem-do-tempo%2F2xa2YdiOJXQt&usg=AOvVaw2AqEcGiW1tBDpfIqpHCT5o',
    }
];

server.get('/', (req, res) =>{ //metodoq exibe algo na tela quando o endereço terminar em /
    res.send('Servidor Vivo');
})

server.get('/trilhas', (req, res) =>{
    res.send(artigos);
})

server.get('/trilhas/:id', (req, res) =>{
    let id = req.params.id;
    let art = artigos.filter(p => p.id == id)[0];
    res.json(art);    
})

server.listen(3000, () => console.log('ta vivo')) //roda o servidor